"""Second commit

Revision ID: 3e63f1be2e9c
Revises: a6e2ae3c4462
Create Date: 2025-05-22 02:26:16.710434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e63f1be2e9c'
down_revision: Union[str, None] = 'a6e2ae3c4462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_id'), 'temporary', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temporary_id'), table_name='temporary')
    op.drop_table('temporary')
    # ### end Alembic commands ###
